// Real-WebGPU stress run — exercises memory paths the happy-path smoke can't:
// aggressive seeding (low Seed FA + max Density) drives many adaptive batches and
// windowed readbacks. It then waits for the PREVIEW phase to finish (not just the
// Save button) and records: streamline count, whether the run reported
// PARTIAL/truncated, whether the 3D preview rendered or fell back to its OOM
// message, and whether the saved TRX parses. Writes e2e/large-data-report.md so
// the "run and record the large-data protocol" gate has evidence.
//
// Honest scope: on a machine with ample RAM this does NOT force a host OOM — it
// proves the real multi-batch tracking + windowed readback + preview + save path
// and the preview success/failure branch the status reports. For full coverage,
// also run a genuinely large DWI on a memory-constrained machine. The adaptive
// salvage DECISION logic is unit-tested in tracking/backoff.test.ts.
//
// Exit codes: 0 = passed, 1 = failed, 75 = skipped (no Chrome/GPU) — distinct so
// release tooling can tell "not run" from "passed".
//
// Run: npm run test:stress   (builds, then drives system Chrome; CHROME_PATH override)

import { spawn } from 'node:child_process'
import {
  existsSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { unzipSync } from 'fflate'
import puppeteer from 'puppeteer-core'

const PORT = 4318
const BASE = '/dwi2trx/'
const APP_URL = `http://localhost:${PORT}${BASE}`
const CHROME =
  process.env.CHROME_PATH ||
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
const REPORT = 'e2e/large-data-report.md' // run from the project root
const PASS = 0
const FAIL = 1
const SKIP = 75

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

function startPreview() {
  return spawn(
    'npx',
    ['vite', 'preview', '--port', String(PORT), '--strictPort'],
    { stdio: ['ignore', 'pipe', 'inherit'] },
  )
}

async function waitForServer(isDead, timeoutMs = 20000) {
  const deadline = Date.now() + timeoutMs
  while (Date.now() < deadline) {
    if (isDead()) throw new Error(`preview exited — port ${PORT} busy?`)
    try {
      if ((await fetch(APP_URL)).ok) return
    } catch {}
    await sleep(200)
  }
  throw new Error(`preview never ready at ${APP_URL}`)
}

// Same finished-download contract as smoke.mjs: parse success is the completion
// condition, because Chrome can expose the final filename before all bytes are
// readable.
async function waitForParsedTrx(dir, timeoutMs) {
  const deadline = Date.now() + timeoutMs
  let lastSize = -1
  let lastError = ''
  while (Date.now() < deadline) {
    const entries = readdirSync(dir)
    const inProgress = entries.some((f) => f.endsWith('.crdownload'))
    const done = entries.find(
      (f) => f.endsWith('.trx') && !f.endsWith('.crdownload'),
    )
    if (done && !inProgress) {
      const path = join(dir, done)
      const size = statSync(path).size
      if (size > 0 && size === lastSize) {
        try {
          return parseTrx(readFileSync(path))
        } catch (err) {
          lastError = err?.message ?? String(err)
        }
      }
      lastSize = size
    }
    await sleep(200)
  }
  throw new Error(
    `no complete parseable .trx download appeared within ${timeoutMs}ms` +
      (lastError ? `; last parse error: ${lastError}` : ''),
  )
}

function parseTrx(buf) {
  const files = unzipSync(new Uint8Array(buf))
  const hn = Object.keys(files).find((k) => k.endsWith('header.json'))
  if (!hn) throw new Error('TRX has no header.json')
  const header = JSON.parse(new TextDecoder().decode(files[hn]))
  return header.NB_STREAMLINES ?? 0
}

function writeReport(obs, status) {
  const stamp = new Date().toISOString()
  const gb = (n) => (n == null ? '?' : (n / 1e9).toFixed(2))
  writeFileSync(
    REPORT,
    [
      '# Large-data / stress run — recorded evidence',
      '',
      `Generated by \`npm run test:stress\` at ${stamp}.`,
      '',
      `- Result: **${status}**`,
      `- Adapter: maxBufferSize ${gb(obs.maxBufferSize)} GB, maxStorageBufferBindingSize ${gb(obs.maxStorageBufferBindingSize)} GB`,
      '- Scenario: sample DWI, Seed FA 0.1, Density 4 (aggressive — many adaptive batches + windowed readbacks)',
      `- Outcome: ${obs.outcome ?? 'n/a'}`,
      `- Streamlines in parsed TRX: ${obs.streamlines ?? 'n/a'}`,
      `- Tracking+preview time: ${obs.elapsedMs ?? 'n/a'} ms`,
      `- Reported PARTIAL/truncated: ${obs.partial ?? 'n/a'}`,
      `- 3D preview rendered: ${obs.previewRendered ?? 'n/a'}`,
      `- 3D preview OOM fallback: ${obs.previewOom ?? 'n/a'}`,
      `- Save TRX enabled + TRX parsed: ${obs.saved ?? 'n/a'}`,
      `- Final status: ${obs.finalStatus ? `"${obs.finalStatus}"` : 'n/a'}`,
      '',
      'Scope: ample-RAM machines will not force a true host OOM here; this proves the',
      'real multi-batch tracking + windowed readback + preview + save path and the',
      'preview success/failure reporting branch. Force a true OOM by running a large',
      'DWI on a memory-constrained machine; salvage decision logic is unit-tested in',
      '`src/dwi2trx/tracking/backoff.test.ts`.',
      '',
    ].join('\n'),
  )
  console.log(`→ wrote ${REPORT}`)
}

async function main() {
  const obs = {}
  if (!existsSync(CHROME)) {
    console.log(`SKIP: no Chrome at ${CHROME} — set CHROME_PATH.`)
    writeReport(obs, 'SKIPPED (no Chrome)')
    process.exit(SKIP)
  }
  const preview = startPreview()
  let exited = false
  preview.on('exit', () => {
    exited = true
  })
  const dir = mkdtempSync(join(tmpdir(), 'dwi2trx-stress-'))
  let browser
  let exitCode = FAIL
  let status = 'FAILED'
  try {
    await waitForServer(() => exited)
    browser = await puppeteer.launch({
      executablePath: CHROME,
      headless: 'new',
      args: [
        '--enable-unsafe-webgpu',
        '--enable-features=Vulkan,WebGPU',
        '--no-sandbox',
        '--use-mock-keychain',
      ],
    })
    const page = await browser.newPage()
    page.on('console', (m) => {
      const t = m.text()
      if (/error|warn|webgpu|dawn|tint|oom|memory/i.test(t)) {
        console.log(`  [page] ${t}`)
      }
    })
    const client = await page.target().createCDPSession()
    await client.send('Page.setDownloadBehavior', {
      behavior: 'allow',
      downloadPath: dir,
    })
    await page.goto(APP_URL, { waitUntil: 'domcontentloaded', timeout: 30000 })

    const adapter = await page.evaluate(async () => {
      if (!navigator.gpu) return null
      const a = await navigator.gpu.requestAdapter().catch(() => null)
      return a
        ? {
            maxBufferSize: a.limits.maxBufferSize,
            maxStorageBufferBindingSize: a.limits.maxStorageBufferBindingSize,
          }
        : null
    })
    if (!adapter) {
      console.log('SKIP: no WebGPU adapter in this browser')
      writeReport(obs, 'SKIPPED (no WebGPU adapter)')
      exitCode = SKIP
      status = null
      return
    }
    Object.assign(obs, adapter)

    console.log('→ load sample + fit')
    await page.waitForSelector('#maskFitBtn:not([disabled])', {
      timeout: 60000,
    })
    await page.click('#maskFitBtn')
    await page.waitForSelector('#saveMapsBtn:not([disabled])', {
      timeout: 120000,
    })

    console.log('→ set aggressive seeding (Seed FA 0.1, Density 4)')
    await page.evaluate(() => {
      const set = (id, v) => {
        const el = document.getElementById(id)
        el.value = String(v)
        el.dispatchEvent(new Event('input', { bubbles: true }))
        el.dispatchEvent(new Event('change', { bubbles: true }))
      }
      set('seedFa', 0.1)
      set('seedDensity', 4)
    })

    console.log('→ generate streamlines (stress) + wait for PREVIEW to finish')
    const t0 = Date.now()
    await page.click('#trackBtn')
    // Terminal states: a "saved as TRX" status is only set AFTER the preview
    // render resolves/rejects, so it proves the preview phase completed (rendered
    // or caught). A "tracking failed"/"No streamlines" status is a hard failure.
    let final = ''
    const deadline = Date.now() + 300000
    while (Date.now() < deadline) {
      await sleep(400)
      const s = await page
        .$eval('#status', (e) => e.textContent.trim())
        .catch(() => '')
      if (/saved as TRX/i.test(s)) {
        final = s
        break
      }
      if (/tracking failed|No streamlines survived/i.test(s)) {
        final = s
        break
      }
    }
    obs.elapsedMs = Date.now() - t0
    obs.finalStatus = final
    if (!final) throw new Error('timed out waiting for the preview to finish')
    if (!/saved as TRX/i.test(final)) {
      obs.outcome = 'hard-failure'
      throw new Error(`tracking hard-failed: ${final}`)
    }

    obs.partial = /partial/i.test(final)
    obs.previewOom = /3D preview (ran out of memory|failed)/i.test(final)
    obs.previewRendered = !obs.previewOom
    obs.saveEnabled = await page.$eval('#saveBtn', (e) => !e.disabled)
    if (!obs.saveEnabled) throw new Error('Save TRX is disabled after a run')

    console.log('→ save + parse TRX (waiting for a complete download)')
    await page.click('#saveBtn')
    obs.streamlines = await waitForParsedTrx(dir, 30000)
    if (obs.streamlines <= 0)
      throw new Error('TRX parsed but has 0 streamlines')
    obs.saved = true
    obs.outcome = obs.partial
      ? 'partial-salvage'
      : obs.previewOom
        ? 'tracked-preview-oom (Save preserved)'
        : 'full-success (preview rendered)'

    console.log(
      `\nPASS — ${obs.outcome}: ${obs.streamlines.toLocaleString()} streamlines, ` +
        `${obs.elapsedMs} ms.`,
    )
    status = 'PASSED'
    exitCode = PASS
  } catch (err) {
    console.error(`\nFAIL: ${err.message}`)
    status = 'FAILED'
    exitCode = FAIL
  } finally {
    if (browser) await browser.close().catch(() => {})
    preview.kill('SIGTERM')
    rmSync(dir, { recursive: true, force: true })
    if (status) writeReport(obs, status)
  }
  process.exit(exitCode)
}

main()
